### PR TITLE
Translate into spanish the section_1/lesson_1 of solidity_smart contracts

### PR DESCRIPTION
**Pull request by jesinnott**
This is the translation into spanish for section 1 / lesson 1 of solidity smart contracts.

Issue #269

### CODE REVIEW

**Comment by adilanchian** [comment]
@jesinnott -

YESSSSSS. Thank you for this it's freaking exciting. I do plan on taking a look at all of these this week and getting them in. It may just take a bit more time than other PRs.

Just want to let you know I am working on it :)

Thank you again for this! So so exciting to see

**Comment by jesinnott** [comment]
> @jesinnott -
> 
> YESSSSSS. Thank you for this it's freaking exciting. I do plan on taking a look at all of these this week and getting them in. It may just take a bit more time than other PRs.
> 
> Just want to let you know I am working on it :)
> 
> Thank you again for this! So so exciting to see

Thanks for doing that. I'll try to help on spanish documentation as much as I can. Mostly over the weekends because of my job. In the future if you are planning to launch it in Spanish I can help in some kind of Spanish Discord channel as well.  I've been answeing questions all the weekend there! 🚀

**Review by emboslicev2 — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @jesinnott !

Sorry for the late reply here :). I think I'm going to make an Issue for each of these projects and keep track of the lessons on there for what we have in progress / finished!

**Comment by adilanchian** [comment]
Yo @jesinnott ! Sorry for the late reply here :)

DM me on Discord! would love to chat more about translations `alec#8853`

**Pull request closed without merging**
