### PR TITLE
CN translation of Lesson 1

### PR DESCRIPTION
**Pull request by TeaTableTT**

### CODE REVIEW

**Comment by TeaTableTT** [comment]
Lesson 1 is translated. Please review.

**Review by helloitsm3 — APPROVED** [review]
CN Translation of Lesson 1

**Comment by adilanchian** [comment]
Sup @TeaTableTT !

Sorry for the late reply here :). This is pretty sick! Can you highlight the files you changed? IT looks like you started another folder with the copied content which is fine :)

**Comment by bobjiang** [comment]
> Sup @TeaTableTT !
> 
> Sorry for the late reply here :). This is pretty sick! Can you highlight the files you changed? IT looks like you started another folder with the copied content which is fine :)

Hi sir, please close this pr, I will summarize all translation files in a batch for Project 1.
thanks a lot .

**Comment by adilanchian** [comment]
@bobjiang - will go ahead and close this up :). Thanks!

**Pull request closed without merging**
