### PR TITLE
Solidity and smart contracts translation to Malay/Bahasa

### PR DESCRIPTION
**Pull request by MuhdRaffiq**
Hi devs! I am interested in using the Buildspace course/project to teach Malaysians/Indonesians about smart contracts. I have pushed translations made by my friends and me from our blockchain community called SummerWatch. Thanks!

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @MuhdRaffiq -

Thanks so much for this!! Yes more than welcome to translate! We are currently working on figuring out a way to get these in so it will stay here for now!

Stay tuned!!!

**Comment by MuhdRaffiq** [comment]
Hey @adilanchian adilanchian, I wonder if it is possible to use the translation in buildspace. I am looking forward to teach smart contracts programming to Malaysian/Indonesian crowd under our community. Have been an avid learner in buildspace and i would like to spread the buildspace course in Malaysia and Indonesia. lemme know if i can help in any way

**Comment by adilanchian** [comment]
BRO THIS IS LIT @MuhdRaffiq 

Sorry for the late reply here :)

DM me on Discord! would love to chat more about translations `alec#8853`

**Comment by helloitsm3** [comment]
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

**Pull request closed without merging**
