### PR TITLE
Translation of 4 courses to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by danicuki**
Translation by the web3dev community

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
This is incredible! THANK YOU SO MUCH!

**Comment by danicuki** [comment]
Much more coming! ;-)

**Comment by cesargatica** [comment]
@danicuki Thanks a lot!!

**Comment by danicuki** [comment]
We added another course translated to the list: NFT Games

**Comment by danicuki** [comment]
we've added solana courses to the PR

**Comment by helloitsm3** [comment]
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

**Pull request closed without merging**
