### PR TITLE
Fixes issue in mintCharacterNFTAction function

### PR DESCRIPTION
**Pull request by jafman**
Fixes issue stopping mintCharacterNFTAction function from triggering.

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
Hi! Thanks a bunch for this. Could you please add a bit more detail about what the issue was? I can take a guess, I just want to make sure I'm understanding it.

**Comment by jafman** [comment]
`const mintCharacterNFTAction = (characterId) => async () => {` returns a function that is never called.

so the `onclick` event below does not fire.

`<button
        type="button"
        className="character-mint-button"
        onClick={()=> mintCharacterNFTAction(index)}
      >{Mint ${character.name}}</button>`

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
Thank you!

**Comment by jafman** [comment]
> Thank you!

My pleasure ...

**Pull request merged**
