### PR TITLE
Translate to spanish polygon ens section 0

### PR DESCRIPTION
**Pull request by jhonnyV-V**
let me know if there's something I should be aware of or something I missed

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @jhonnyV-V !

Thanks for this :). Currently in the process of getting translations setup properly :). Will get this reviewed and merged in at some point! 

Stay tuned!

**Comment by adilanchian** [comment]
Yo @jhonnyV-V ! Sorry for the late reply here :)

DM me on Discord! would love to chat more about translations `alec#8853`

**Comment by jhonnyV-V** [comment]
> alec#8853

Hi, I just dm you

**Comment by cesargatica** [comment]
@helloitsm3

**Comment by helloitsm3** [comment]
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

**Pull request closed without merging**
