### PR TITLE
Typo in Section 1 Lesson 4

### PR DESCRIPTION
**Pull request by jjohnson5253**

### CODE REVIEW

**Comment by adilanchian** [comment]
Very nice catch :). Thank you for this!!

**Comment by adilanchian** [comment]
@all-contributors please add @jjohnson5253  for doc

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

**Comment by jjohnson5253** [comment]
Thank you! :) Love the project! ❤️

**Pull request merged**
