### PR TITLE
front/back end changes to attackComplete event

### PR DESCRIPTION
**Pull request by scott-a-m**
Changes proposed for both solidity contract (section 2.3) and front-end (section 3.6) code for the `attackComplete` event. Added `msg.sender` as a parameter to be emitted in the event so that we can check on the front end whether the attack has come from our own player or not.

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
Hey Scott! Thanks a bunch for this. Could you change the wording here to be more consistent with the rest of the project?

> Notice how we also passed `msg.sender` as a parameter so that we can check on the front-end later whether the attack has come from our address or someone else's.

> which we will then use to update the state of both our boss and character NFT (or just the boss if the attacking character isn't ours).

**Comment by scott-a-m** [comment]
No problem. I've made some further changes. Hopefully the style is okay now. If still not, let me know what to type and will finalise it for you :-)

**Comment by scott-a-m** [comment]
Sorry, just checked files and it seems my IDE has reformatted the pages, let me commit the files again....

**Comment by scott-a-m** [comment]
Okay, changes have now been made and previous formatting restored. Please give it a look :-)

**Pull request closed without merging**
