### PR TITLE
change to `ERC721Enumerable`

### PR DESCRIPTION
**Pull request by thomastraum**
worth changing to 'ERC721Enumerable':
https://discord.com/channels/869321815833575434/869331605662101546/926589199824592966

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @thomastraum -

This is an AWESOME catch. Love this. Will get it done <3.

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈

**Comment by adilanchian** [comment]
@all-contributors please add @thomastraum for doc

**Comment by thomastraum** [comment]
thanks guys! stoked I was able to help. keep up the good work!

**Pull request merged**
