### PR TITLE
Update Lesson_1_Get_Local_Solana_Env_Running.md

### PR DESCRIPTION
**Pull request by chiarawilden**
Typo

### CODE REVIEW

**Review by adilanchian — APPROVED** [review]
Hi there!

Very nice catch! Thanks for taking the time to make this contribution :)

**Comment by adilanchian** [comment]
ALSO YOU MADE YOUR FIRST CONTRIBUTION - NICE!!!

💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜💜

**Comment by adilanchian** [comment]
@all-contributors please add @chiarawilden  for doc

**Comment by chiarawilden** [comment]
Hahahahah there's some more where that came from 😏

I'll add them in a bit 💜

**Pull request merged**
