### PR TITLE
Update Lesson_4_Create_A_Contract_That_Mints_NFTs.md

### PR DESCRIPTION
**Pull request by cesargatica**
Translation to Spanish of Section_1 Lesson_4

### CODE REVIEW

**Comment by helloitsm3** [comment]
@cesargatica please do a pull to get the updated content and fix any conflicts on your side. Thanks

**Comment by cesargatica** [comment]
Hello @helloitsm3 anything else i need to do? Thanks.

**Comment by helloitsm3** [comment]
You only need to do on PRs that has merge conflicts

**Comment by helloitsm3** [comment]
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

**Pull request closed without merging**
