### PR TITLE
Typos in line 123

### PR DESCRIPTION
**Pull request by lakshyaag**
Some typos in the lesson page.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @lakshyaag -

Nice catch!!! Thank you for this :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱

**Comment by adilanchian** [comment]
@all-contributors please add @lakshyaag for doc

**Comment by lakshyaag** [comment]
> ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION
> 
> 🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱

Thank you so much! ❤

**Pull request merged**
