### PR TITLE
added sudo prefix

### PR DESCRIPTION
**Pull request by phenomenon98**
Added sudo prefix to mocha install and yarn install commands. It throws a bunch of errors without it as we are installing globally

### CODE REVIEW

**Comment by adilanchian** [comment]
Hmmm so `sudo` in this context only elevates the shell to admin privileges. What were the errors that you were getting here?

This shouldn't affect anything!

**Comment by phenomenon98** [comment]
image

Throws permission errors

**Comment by adilanchian** [comment]
Roger!

Okay - so I don't think this should be an overall terminal change, but a note that says something along the lines of:

"Note: if you have an issue with permissions try running this command with sudo in front of it!" Or something along those lines

**Review by adilanchian — CHANGES_REQUESTED** [review]
See comment above please :)

**Comment by adilanchian** [comment]
Sup @phenomenon98 !

Just checking in here :)

**Comment by adilanchian** [comment]
Hey @phenomenon98 - 

Going to close out this PR for now as I actually haven't seen any other issues expressed about this! Thanks :)

**Pull request closed without merging**
