### PR TITLE
NPM not working on windows

### PR DESCRIPTION
**Pull request by IMPranshu**
No solution on the web. Instead yarn perfectly does the job

### CODE REVIEW

**Comment by IMPranshu** [comment]
# Error when using npm for openzeppelein/contracts
image

# Success when using yarn instead
image

**Comment by AlmostEfficient** [comment]
Hi, this looks troublesome, thanks for bringing it up!

Could you please let me know what version of NPM/Node you're running and which Windows build you're on? Thanks!

**Comment by IMPranshu** [comment]
I am on Windows 10 and my node -v16.14.0 & npm -v8.5.1

**Comment by AlmostEfficient** [comment]
Seems this was an issue with the NPM registry servers. It's working now! Thanks for the contribution!

**Pull request closed without merging**
