### PR TITLE
Add chainlink faucet to Section_2 - Lesson_2 of Solidity_and_smart_contracts 

### PR DESCRIPTION
**Pull request by JoaquimLey**
Since all the faucets listed on the current live version of the doc didn't work for me (no ETH to send or failing Tx) I google for alternatives and this one from Chainlink works quite well.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @JoaquimLey !

Thanks or this addition! I feel like we can always use more faucet links hehe. Out of curiosity - did the buildspace bot not work on Discord?

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖

**Comment by adilanchian** [comment]
@all-contributors please add @JoaquimLey  for doc

**Comment by JoaquimLey** [comment]
> Hey @JoaquimLey !
> 
> Thanks or this addition! I feel like we can always use more faucet links hehe. Out of curiosity - did the buildspace bot not work on Discord?

Just FYI the faucet never worked, I did try it :|

**Pull request merged**
