### PR TITLE
Replace broken faucet

### PR DESCRIPTION
**Pull request by developing-coder**

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @developing-coder !

Is the faucet completely broken or just doesn't have any funds? We can just add this one on if anything!

**Comment by developing-coder** [comment]
Hey @adilanchian ! :)

I get a 404 Not Found error when trying to access the [Ethily faucet](https://ethily.io/rinkeby-faucet/). Is it working for you?

**Comment by NickGonzalez04** [comment]
@developing-coder thanks for the update! I checked it out Ethily doesn't seem like a website. Definitely to be removed :)
Can you make sure you pull latest so we can merge and update this change!

**Comment by developing-coder** [comment]
This particular file was last changed 2 months ago and my changes are from 12 days ago. Should be good...

**Comment by adilanchian** [comment]
@NickGonzalez04 @developing-coder ya we are good to go here! TY!

**Pull request merged**
