### PR TITLE
Update instructions to disconnect wallet

### PR DESCRIPTION
**Pull request by developing-coder**
- Change instructions to reflect working with Replit vs local environment
- Replace connected sites image to show a connection to a Replit site vs local environment
- Minor grammatical improvements

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @developing-coder -

This is a great change, but this project actually supports but Replit and local dev! This means we need to keep both versions of this. Can you make this change?

Thanks!!

**Review by adilanchian — CHANGES_REQUESTED** [review]
Left some thoughts

**Comment by developing-coder** [comment]
> Hey @developing-coder -
> 
> This is a great change, but this project actually supports but Replit and local dev! This means we need to keep both versions of this. Can you make this change?
> 
> Thanks!!

Ah, OK. Didn't realize.

Added the change you requested.

**Review by helloitsm3 — APPROVED** [review]
LGTM

**Review by AlmostEfficient — APPROVED** [review]

**Pull request merged**
