### PR TITLE
Added steps to change Phantom wallet to Devnet and get Sol from a faucet 🚰

### PR DESCRIPTION
**Pull request by faceyacc**
I added steps to show builder how to change Phantom wallet to Devnet and how to get SOL to use a play money from a faucet.

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
Hi, this is pretty cool, thanks a bunch for contributing! Could you please upload the image or Imgur instead?

**Comment by AlmostEfficient** [comment]
Thanks for that! I've just changed the formatting to markdown. Last request - could you delete the uploaded assets?

**Comment by faceyacc** [comment]
Sorry for the confusion, I'm not use to committing to projects haha. I removed the png assets; let me know if I need anything to ship this. 🚀

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
Nice, way to go!

**Pull request merged**
