### PR TITLE
Update Lesson_1_Call_Candy_Machine_From_App.md

### PR DESCRIPTION
**Pull request by shaikharfan7**

### CODE REVIEW

**Review by aftr101 — APPROVED** [review]

**Review by recurshawn — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @shaikharfan7 !

I just merged in this change earlier so will close this one up, but you'll def get credit for this!! Thank you :)

**Comment by adilanchian** [comment]
@all-contributors please add @shaikharfan7  for doc

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺

**Comment by shaikharfan7** [comment]
Thank you so much @adilanchian, I look forward to contributing more to buildspace

**Pull request closed without merging**
