### PR TITLE
Super minor grammatical error :)

### PR DESCRIPTION
**Pull request by ashispavan**

### CODE REVIEW

**Comment by adilanchian** [comment]
SUP @ashispavan !

Nice catch and thanks for the addition :)

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION 

🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄

**Comment by adilanchian** [comment]
@all-contributors please add @ashispavan  for doc

**Comment by ashispavan** [comment]
> ALSO CONGRATS ON YOUR FIRST CONTRIBUTION
> 
> 🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄

Thank you!!!!

**Pull request merged**
