### PR TITLE
Added directory structure for .env file.

### PR DESCRIPTION
**Pull request by shaikharfan7**
Noticed that a lot of people are putting their .env file under /src instead of /app that's causing them to encounter errors so added a proper directory structure route for the same.

### CODE REVIEW

**Review by recurshawn — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @shaikharfan7 !

Sorry for the insanely late reply here 😅

Ya this is great!! Thank you so much for the addition

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈

**Comment by adilanchian** [comment]
@all-contributors please add @shaikharfan7 for doc

**Comment by shaikharfan7** [comment]
Haha, no worries. Glad to be contributing to buildspace.

**Pull request merged**
