### PR TITLE
Add code so submitting a GIF adds it to the array

### PR DESCRIPTION
**Pull request by quuu**
Without this bit of instruction, user's code will just have a text field that accepts input, but does nothing except print on submitting

### CODE REVIEW

**Review by adilanchian — CHANGES_REQUESTED** [review]
Looks like a really good change honestly!

Can you do me a favor? Can you make sure that any other lesson that references this function is updated?

Appreciate the change!

**Comment by quuu** [comment]
Updated other instances of sendgif

**Comment by quuu** [comment]
> Looks like a really good change honestly!
> 
> Can you do me a favor? Can you make sure that any other lesson that references this function is updated?
> 
> Appreciate the change!

Found one other instance where sendGif is rewritten, added clearing logic to that... no need to change gifList because getGifList does it already

**Review by adilanchian — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @quuu -

Thanks for this! Looking good on my end here :). Thank you for this!

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION !!

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

**Comment by adilanchian** [comment]
@all-contributors please add @quuu  for doc

**Pull request merged**
