### PR TITLE
anymose

### PR DESCRIPTION
**Pull request by anymose96**
Lesson_2_Write_Your_First_Smart_Contract.md

### CODE REVIEW

**Review by helloitsm3 — COMMENTED** [review]
Doesn't include any Chinese translation at all. Please include it if you want it to be approve

**Comment by bobjiang** [comment]
> Doesn't include any Chinese translation at all. Please include it if you want it to be approve

sorry sir, we are working on it, and team member did a pr early. 
will work on it and publish the course (project) 1 once done.

just on hold for this pr.

**Comment by adilanchian** [comment]
Hey @bobjiang !

Thanks for this :). If you can point me to the lessons that you have actually translated that would be awesome! We are still in the process of trying to understand the best way to get these translations together

So lets start here and then we can streamline this a bit :).

TY!

**Comment by bobjiang** [comment]
I will create another pr for project one. Please close this one.

**Pull request closed without merging**
