### PR TITLE
Reduce airdrop volume to 2

### PR DESCRIPTION
**Pull request by snamber**
Requesting an airdrop of 5 results in "balance unchanged".
```
snamber@Stefans-MacBook-Air ~/s/buildspace-myepicproject> solana airdrop 5
Requesting airdrop of 5 SOL

Signature: y1kzQ6FXbYHyGYjjphbvQBMGpiqSh5jHG3knvCGbcBWTgPLa18yjzHKt2kModho4BxSQ4dnRJ1YuAuvSKA6pjNV

Balance unchanged
Run `solana confirm -v y1kzQ6FXbYHyGYjjphbvQBMGpiqSh5jHG3knvCGbcBWTgPLa18yjzHKt2kModho4BxSQ4dnRJ1YuAuvSKA6pjNV` for more info
```

Checking the details of the action shows that the limit currently is set to 2 SOL. (`"request too large; req: ◎5, cap: ◎2"`)
```
snamber@Stefans-MacBook-Air ~/s/buildspace-myepicproject> solana confirm -v y1kzQ6FXbYHyGYjjphbvQBMGpiqSh5jHG3knvCGbcBWTgPLa18yjzHKt2kModho4BxSQ4dnRJ1YuAuvSKA6pjNV
RPC URL: https://api.devnet.solana.com
Default Signer Path: /Users/snamber/.config/solana/id.json
Commitment: confirmed

Transaction executed in slot 100600488:
  Block Time: 2021-12-13T12:05:39+01:00
  Recent Blockhash: 9fSdYUgD7E2p45Av5dsKY6w4Cc49q83tF2uosjr7QxUJ
  Signature 0: y1kzQ6FXbYHyGYjjphbvQBMGpiqSh5jHG3knvCGbcBWTgPLa18yjzHKt2kModho4BxSQ4dnRJ1YuAuvSKA6pjNV
  Account 0: srw- 9B5XszUGdMaxCZ7uSQhPzdks5ZQSmWxrmzCSvtJ6Ns6g (fee payer)
  Account 1: -r-x MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr
  Instruction 0
    Program:   MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr (1)
    Data: "request too large; req: ◎5, cap: ◎2"
  Status: Ok
    Fee: ◎0.000005
    Account 0 balance: ◎311222.673736265 -> ◎311222.673731265
    Account 1 balance: ◎0.52149888
  Log Messages:
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]
    Program log: Memo (len 39): "request too large; req: ◎5, cap: ◎2"
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed 32814 of 200000 compute units
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr success

Finalized
```

Deploying the contract to devnet requires more than 2 SOL at the moment, thus the addition of running the command "twice".

### CODE REVIEW

**Review by shaikharfan7 — APPROVED** [review]

**Review by helloitsm3 — APPROVED** [review]

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hey @snamber !!

Sorry for the late reply here :). 

Ya this looks sick!! Can you do me a favor - can you just pull the latest from out remote here into your fork?

I actually just pushed some changes in that accounted for some of this, but didn't I like your text changes :).

TY!

**Comment by snamber** [comment]
Ha, it's only a tiny change but I appreciate the enthusiasm! 😄
I merged your `main` into the patch

Cheers,
Stefan

**Comment by adilanchian** [comment]
@snamber 

All changes are appreciated out here !! Awesome will get this in

**Comment by adilanchian** [comment]
@all-contributors please add @snamber for doc

**Pull request merged**
