### PR TITLE
Fix/formatting suggestions

### PR DESCRIPTION
**Pull request by oli-clive-griffin**
just a few minor changes to to code formatting :)

### CODE REVIEW

**Review by adilanchian — APPROVED** [review]
Really nice changes all around. Thanks for taking the time to submit this

**Comment by adilanchian** [comment]
@all-contributors please add @oli-clive-griffin  for doc

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION 

🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄

**Comment by oli-clive-griffin** [comment]
Thanks man!!! stoked to help!

**Pull request merged**
