### PR TITLE
Update declaration of waveTxn variable

### PR DESCRIPTION
**Pull request by ABusyHippie**
Update "const" declaration of waveTxn variable to "let" since when final bits of code are added waveTxn changes and keeping const declaration throws an error. 

Just declare as "let" to begin with for consistency and with anticipation that variable will be updated further in lesson

### CODE REVIEW

**Comment by adilanchian** [comment]
Ahh yes I can understand how this could get confusing haha. 

Thanks for the updates!

**Comment by adilanchian** [comment]
@all-contributors please add @ABusyHippie  for doc

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION!!!

THIS IS SICK.

**Comment by ABusyHippie** [comment]
Thanks! Happy to help :)

**Pull request merged**
