### PR TITLE
Fix bad translations and a seriously bad thing

### PR DESCRIPTION
**Pull request by julian-pineiro**
Corrected some bad translations. There is currently a sentence that translates to "worst case scenario, you get involved with some crypto drug lords" which sounds pretty unprofessional and misleading.

### CODE REVIEW

**Comment by julian-pineiro** [comment]
I decided to create this Pull Request because the current accepted translation is very inappropiate. This is my way of paying back a little to this project.

**Comment by julian-pineiro** [comment]
@adilanchian I tag you here because I saw you were commenting other translations :) Hope this helps.

**Comment by adilanchian** [comment]
sup @julian-pineiro !

Thanks for calling this out :). You made a few changes here can you point out the sentence you are talking about 🤔 . I can't seem to see it?

**Comment by julian-pineiro** [comment]
Hi @adilanchian! Line 108: "¿Qué es lo peor que puede pasar? ¿Te conectas a algunas empresas de crypto de drogas?"
"What's the worst that could happen? You get involved in some crypto drug companies?"

**Comment by adilanchian** [comment]
Hey @julian-pineiro !

Sorry totally missed this lmao. Also - sorry for the late reply here!! Working hard to get this reviewed asap :). 

Thank you again for bringing this up :)

**Comment by adilanchian** [comment]
Hey @julian-pineiro !

Cheers for this :). I actually need to test something out here to make sure things work as expected before I merge it haha. But this looks great!!

**Comment by adilanchian** [comment]
Hey @julian-pineiro -

I haven't forgotten about you! Trying to get this done sometime this week :)

**Pull request closed without merging**
