### PR TITLE
Update Lesson_1_Get_Your_Local_Ethereum_Network_Running.md

### PR DESCRIPTION
**Pull request by constanteen**
Tried running on my system with Node 15 and I encountered an error: "You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all."  Did some research and found this useful https://hardhat.org/reference/stability-guarantees.html

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
This is great! Can you add a link to the NodeJS releases page (https://nodejs.org/en/about/releases/) so people can find out which version they should be running?

**Review by AlmostEfficient — CHANGES_REQUESTED** [review]
This is great! Can you add a link to the NodeJS releases page (https://nodejs.org/en/about/releases/) so people can find out which version they should be running? Something like

> We recommend running Hardhat using the current LTS Node.js version or you may run into some issues! You can find the current releases [here](https://nodejs.org/en/about/releases/).

**Comment by constanteen** [comment]
Yeah. This looks better. Thanks. I updated it.

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
@all-contributors please add @constanteen for documentation

**Pull request merged**
