### PR TITLE
fix: typo in Solana_And_Web3 >> Lesson_2

### PR DESCRIPTION
**Pull request by samicey**
Hi @farzaa, This PR fixes a typo I saw while taking the Learn Solana_And_Web3  course.

Kindly review the PR.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @samicey - 

VERY NICE. Thanks for the catch :)

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION!!

⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️⚔️

**Comment by adilanchian** [comment]
@all-contributors please add @samicey  for doc

**Comment by samicey** [comment]
Thanks @farzaa.

**Pull request merged**
