### PR TITLE
The Ethily Faucet was broken

### PR DESCRIPTION
**Pull request by 0xJepsen**
I replaced it with the chainlink faucet

### CODE REVIEW

**Comment by dcts** [comment]
Yes I experienced that too!

**Comment by AlmostEfficient** [comment]
Great addition! The Chainlink faucet has far higher uptime! Any chance you can update this for the rest of the projects too?

**Comment by 0xJepsen** [comment]
Yeah, I would be happy to!

**Comment by 0xJepsen** [comment]
Other instances have been updated

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
As the kids say - looks gucci! Thanks!

**Comment by AlmostEfficient** [comment]
@all-contributors please add @0xJepsen for documentation

**Pull request merged**
