### PR TITLE
Edit NFT Game Section 3 Lesson 5.

### LINKED ISSUE #906: ✨ [NFT Browser Game]: <SECTION_3> - <Building the character select page>
### What You Are Changing
Problem:
- `mintCharacterNFTAction` is being called multiple times on render.
- the reason is instead of passing a function to call `mintCharacterNFTAction` to `onClick` on line 141, it calls the function there currently.

Solution:
- Create an arrow function that called `mintCharacterNFTAction` and passed it to `onClick`.
- I'll link my PR here

### Anything else?
Thanks for building these great projects, I've been enjoying it so far! Keep up the good work.

### PR DESCRIPTION
**Pull request by jte0711**
`mintCharacterNFTAction` is being called multiple times on render. The reason is the code is written wrongly and instead of calling `mintCharacterNFTAction` in the `onClick` we should pass a function that calls `mintCharacterNFTAction`.

fix #906

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @jte0711 !

Can you verify that there are no other code blocks using this? If so, can you also update the rest of them with your change :)?

**Comment by jte0711** [comment]
Hi @adilanchian, will do! I haven't checked section 4 yet, I'll let you know when I'm done.

**Comment by jte0711** [comment]
@adilanchian , just updated the commit. I checked the rest of the lessons and Section 4, there shouldn't be anything else related to my changes.

**Comment by adilanchian** [comment]
Hey @jte0711 -

Sounds good!! Thanks for this :)

**Comment by adilanchian** [comment]
@all-contributors please add @jte0711  for doc

**Pull request merged**
