### PR TITLE
More consistent pragma version pinning in NFT Collection 1.4

### PR DESCRIPTION
**Pull request by metasucks**
Not sticking to an exact version seems to be more in sync with previous code samples.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @metasucks -

I think we actually want to stick with `0.8.0` at all times. I think it makes more sense to change all the other references to stay on `0.8.0`. 

Thoughts?

**Comment by metasucks** [comment]
Hey @adilanchian! I went ahead and added a commit with your suggested change. The caret seems to be used quite a bunch, but if it's more stable and predictable with a fixed pin, that could be good for the learning experience.

**Comment by adilanchian** [comment]
Hey @metasucks !

Im so sorry to do this to you - but would you be able to revert this 😅. Was just chatting with Farza about this and it def make more sense to use `^0.8.0` everywhere! 

You're a legend sorry!!

**Comment by metasucks** [comment]
No problem at all @adilanchian! Here to learn and contribute, and both boxes are checked.

I rolled the branch back to the initial commit - no other non-`^0.8.0` pragmas around besides this one.

**Comment by adilanchian** [comment]
POG. Appreciate your help here!

Looks good to me :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by adilanchian** [comment]
@all-contributors please add @metasucks  for doc

**Comment by metasucks** [comment]
:sunglasses: Nice!

**Pull request merged**
