### PR TITLE
Typo Fix - Solana Project

### PR DESCRIPTION
**Pull request by smckisson**
Corrects "specific" to "specify" when describing 'StartStuffOff' context

### CODE REVIEW

**Comment by ABusyHippie** [comment]
I have a small typo change as well, could you add it to your PR? 

In section 1 lesson 4 of the "Build a Web3 App with Solidity + Ethereum Smart Contracts" project the screenshot displaying output of the code changes says "xyzaddress _is_ waved" when it should match the updated WavePortal.sol code which has correct grammar and say "xyzaddress _has_ waved"

**Comment by AlmostEfficient** [comment]
This PR is specifically for the Solana course. Perhaps you could make your own? Would be a great first PR. @ABusyHippie 

@smckisson Could you please add a bit of info in the description so it's easy for maintainers to tell what the PR is about? Makes it easier to group tasks together and speeds up approvals/merges.

**Comment by adilanchian** [comment]
Thanks @AlmostEfficient !!

Also @ABusyHippie this would be ideal! Thank you :)

@smckisson - Thanks for the change! Looks great

**Comment by adilanchian** [comment]
@all-contributors please add @smckisson for doc

**Pull request merged**
