### PR TITLE
Update Lesson_4_Call_Deployed_Contract.md

### PR DESCRIPTION
**Pull request by willworth**
typo

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @willworth !

Great catch :). Thank you for this!

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼🐼

**Comment by adilanchian** [comment]
@all-contributors please add @willworth  for doc

**Comment by willworth** [comment]
Wish I could do something more valuable, but I have to start somewhere...

**Pull request merged**
