### PR TITLE
build solana v1.8.5 instead of v1.8.2

### PR DESCRIPTION
**Pull request by torquan**
Reason:
v.1.8.2 leads to a bug where the function addGif in Section 2 / Lessono 3 won't work.
See https://github.com/project-serum/anchor/issues/1062

Update: In Section 2 / Lesson 4, M1 people will again get stuck. Didn't find a solution to this, and as I've had problems over and over again I've now moved my project to a Ubuntu VPS.
Should have done it sooner, now the tests just run through :)

### CODE REVIEW

**Review by adilanchian — APPROVED** [review]
Whats up @torquan !

Thanks for the PR here :). I am going to tag @NickGonzalez04 to see if he has any thoughts here. This is definitely a good thought to add though!

Nick pretty much wrote this guide :)

**Comment by NickGonzalez04** [comment]
Update on MacM1 instructions for Solana being set to the latest version:
- [x] Test Solana v1.8.5 by doing a git checkout and rebuilding with the command `./scripts/cargo-install-all.sh .`

**Comment by adilanchian** [comment]
Thanks for the updates @NickGonzalez04 :)

**Comment by NickGonzalez04** [comment]
Have Solana 1.9.0 working well. Fleshing out anchor deploy issues. Will have update shortly!

**Comment by NickGonzalez04** [comment]
Went back with 1.8.5 for now. Will test 1.9.0 again, but everything works. Review

- [x] solana-test-validator runs without `--no-bpf-jit`.
- [x]  `anchor test` runs without ` --skip-local-validator` tagged on.
- [x] anchor deploy with no issues :)

**Comment by adilanchian** [comment]
POG thanks @NickGonzalez04  :)

**Comment by adilanchian** [comment]
@torquan thanks for the change!!

**Pull request merged**
