### PR TITLE
Use async/await. Check if `hasVoted` is true/false

### PR DESCRIPTION
**Pull request by kuriakinzeng**
We should check if `hasVoted` is true before console.log"🥵 User has already voted");

### CODE REVIEW

**Comment by adilanchian** [comment]
@kuriakinzeng - 

Please see my comment in PR #717 :)

**Comment by kuriakinzeng** [comment]
Hi @adilanchian I have put all async/await changes in a single PR, and shall close the other two PR's.

**Comment by kuriakinzeng** [comment]
This PR is included in PR #718

**Comment by NickGonzalez04** [comment]
@adilanchian This looks good. Want to confirm first if you wanted all async/await?

@kuriakinzeng could you make sure you are pull from latest from fork's remote origin in case this is an approval PR from Alec ? :)

**Comment by adilanchian** [comment]
@NickGonzalez04 <3333 Yup all fine with that!

@kuriakinzeng - If you can also verify all the conflicts are resolved please :)

**Comment by kuriakinzeng** [comment]
@adilanchian @NickGonzalez04 I've pulled from latest from fork's remote origin and resolved conflicts

**Comment by adilanchian** [comment]
Hey @kuriakinzeng -

So sorry for the late reply here!!!

Looks lit thank you so much :)

**Pull request merged**
