### PR TITLE
Update Lesson_5_Deploy_Locally.md correcting typo

### PR DESCRIPTION
**Pull request by DrTriv**
LINE 54: In the runMain const, when there is an error, it should read "console.log(error)". It currently reads "console.error(error)"

### CODE REVIEW

**Comment by helloitsm3** [comment]
`console.error(error)` is correct since the purpose of it is to output an error message to the console

**Comment by DrTriv** [comment]
Why is it not console.log(error) like it was done in a previous part of the lesson? I believe it should be consistently used.
-------- Original message --------From: Sean ***@***.***> Date: 18/12/2021  14:47  (GMT+00:00) To: buildspace/buildspace-projects ***@***.***> Cc: DrTriv ***@***.***>, Author ***@***.***> Subject: Re: [buildspace/buildspace-projects] Update Lesson_5_Deploy_Locally.md correcting typo (PR #603) 
console.error(error) is correct since the purpose of it is to output an error message to the console

**Comment by adilanchian** [comment]
Hey @DrTriv !

Thanks for the contribution! So I actually don't see this lie of code being used anywhere else in the lesson? Are you talking about in an earlier lesson in the project?

**Comment by adilanchian** [comment]
@DrTriv - Adding a friendly ping here to see if you are interested in doing this still!

**Comment by adilanchian** [comment]
Going to close this for now!

If you feel strongly about it, feel free to open another one!

**Pull request closed without merging**
