### PR TITLE
clearer explanation of how to add setCharacterNFT to App.js

### PR DESCRIPTION
**Pull request by danicuki**

### CODE REVIEW

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hey @danicuki -

Thanks for bringing this into a separate PR!

So I think this should live in the actual content - not as a comment in the code if that makes sense!

**Comment by adilanchian** [comment]
Sup @danicuki !

Just checking in here :)

**Comment by danicuki** [comment]
done

**Review by adilanchian — APPROVED** [review]
Poggg thanks for this!

**Pull request merged**
