### PR TITLE
typo

### PR DESCRIPTION
**Pull request by fox-222**
`my-wave-portal` is project name

### CODE REVIEW

**Review by garyghayrat — APPROVED** [review]
Thank you!

**Review by narendracode — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @fox-222 -

Sorry for the late reply here :(. Very nice catch!!! thank you for this :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

**Comment by adilanchian** [comment]
@all-contributors please add @fox-222  for doc

**Pull request merged**
