### PR TITLE
Update Lesson_2_Call_Deployed_Program.md

### PR DESCRIPTION
**Pull request by donni106**
- corrected a console log to point out the right method name

### CODE REVIEW

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hey @donni106 - 

Thanks for the PR :). Can you do me a huge favor? This code block is probably used in other spots throughout the project. Can you just make sure all instances of this are changed?

**Comment by donni106** [comment]
Did it. I could not find another occurrence.

**Comment by adilanchian** [comment]
@donni106 - LEGEND. Thanks so much for this :)

**Comment by adilanchian** [comment]
@all-contributors please add @donni106  for doc

**Pull request merged**
