### PR TITLE
Chinese translation for project "Solidity_And_Smart_Contracts"

### PR DESCRIPTION
**Pull request by bobjiang**
This pull request includes all 'cn' folders. 
For now the first project "Solidity_And_Smart_Contracts" has been translated into Chinese.

We will work on the translation project by project and pr.

### CODE REVIEW

**Comment by bobjiang** [comment]
I removed all the untranslated content, just leave "project 1 - translated to Chinese", 
please help review once come back from holiday ;)

**Comment by adilanchian** [comment]
Hey @bobjiang !

Sorry for the late reply here :(. This is freaking AWESOME. Thank you for doing this work!!! 

So we are in the midst of trying to figure out how to actually deploy this. We will need to make some backend changes here to support another language. Give us some time and we will get something going here :)

Thanks again!

**Comment by bobjiang** [comment]
> Hey @bobjiang !
> 
> Sorry for the late reply here :(. This is freaking AWESOME. Thank you for doing this work!!!
> 
> So we are in the midst of trying to figure out how to actually deploy this. We will need to make some backend changes here to support another language. Give us some time and we will get something going here :)
> 
> Thanks again!

ok, great!
so I just copy the folder like es language, hope it is not too hard to change.

by the way, could we continue to translate another project?
bc I would translate the first one as a trial ;)

**Comment by adilanchian** [comment]
Yo @bobjiang ! Sorry for the late reply here :)

DM me on Discord! would love to chat more about translations `alec#8853`

**Comment by helloitsm3** [comment]
LGTM!

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
Probably a good idea to squash these before merge :)

**Comment by adilanchian** [comment]
@bobjiang thank you SO MUCH for this -- can you also drop the github accounts for the people that helped you out with this? TY!

**Comment by adilanchian** [comment]
@all-contributors please add @bobjiang for doc

**Comment by adilanchian** [comment]
@all-contributors please add @anymose96 and @Xia-Sam for doc

**Comment by adilanchian** [comment]
@all-contributors please add @Xia-Sam for doc

**Pull request merged**
