### PR TITLE
Fixes Typo in Lesson_1_Get_Local_Solana_Env_Running.md

### PR DESCRIPTION
**Pull request by bleafman**
Fixes typo on line 148.

` it may ask you to update you path` --> ` it may ask you to update your path`

### CODE REVIEW

**Comment by adilanchian** [comment]
Sup @bleafman !

Thanks for this change :). LOOKS GOOD.

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by adilanchian** [comment]
@all-contributors please add @bleafman  for doc

**Comment by bleafman** [comment]
Thanks @adilanchian! Happy to help!

**Pull request merged**
