### PR TITLE
Update Lesson_1_Get_Solana_Running.md - Use moniker instead of full url

### PR DESCRIPTION
**Pull request by matanwrites**
Using moniker instead of hardcoded url as url might one day change to something else.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @matanwrites !

LOVE IT. Thanks for this change :)

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hey @matanwrites !

LOVE IT. Thanks for this change :). Can you do me a favor - can you just checkout the rest of the project to make sure there are no other references of this? If so - just change it to this method please :)

**Comment by matanwrites** [comment]
Hey @adilanchian ran a search on `solana config set --url` there was another occurrence, good catch!

**Comment by adilanchian** [comment]
Sup @matanwrites !

Sorry for the late reply here :(. Looks great! Thanks for the fix!!

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺🕺

**Comment by adilanchian** [comment]
@all-contributors please add @matanwrites  for doc

**Comment by matanwrites** [comment]
@adilanchian 🤩🍻 cheers!!

**Pull request merged**
