### PR TITLE
Create Lesson_1_What_Is_A_NFT.md

### PR DESCRIPTION
**Pull request by cesargatica**
Translation to Spanish Section_1 Lesson_1

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
Hellooooooooooooooooooo! 

Thank you so much for this, it's incredible! Could you please combine all of your PRs into one? I recommend forking this repo and working on your fork so you can add items to it easily over time. 

Please also compare this with https://github.com/buildspace/buildspace-projects/pull/563

**Comment by helloitsm3** [comment]
Please update your content by doing a pull on your side and fix any merge conflicts before pushing. Thanks

**Comment by cesargatica** [comment]
@helloitsm3

**Comment by helloitsm3** [comment]
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

**Pull request closed without merging**
