### PR TITLE
Use double quotes consistently

### PR DESCRIPTION
**Pull request by suud**
Replaced some single quotes by double quotes for consistency throughout the whole file.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @suud -

Thanks or the contribution here! Ahhh yaaa this is a good one! Can you do me a huge favor? If you are going to make this change could you make it for all the files in this project? Should probably be consistent all around!

**Comment by suud** [comment]
Done!

**Comment by adilanchian** [comment]
POG. LGTM!

Thanks sop much for this :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷

**Comment by adilanchian** [comment]
@all-contributors please add @suud for doc

**Pull request merged**
