### PR TITLE
Add Instructions for starting up app

### PR DESCRIPTION
**Pull request by joshtsch**
This PR adds basic instructions for installing dependencies and running the `start` script to get the app the reader has forked running. I feel it's beneficial to assume the reader may have little-to-no prior node/react experience. Every step in the process should be documented for clarity.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @joshtsch !

Thanks for this submission :). Ya this is pretty valid - though we have all these instructions in the README! I feel like it actually makes more sense for the person cloning down the repo to use that, just in case something in that project changes, it's much easier to update the Repo :). 

Maybe we could call out that README? Let me know your thoughts!

**Comment by joshtsch** [comment]
Ah nope, that makes complete sense! Checking the README is a great practice that I've obviously forgotten haha! Updated the PR.

**Comment by adilanchian** [comment]
Hey @joshtsch -

I appreciate it!! Looking good :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION 

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by adilanchian** [comment]
@all-contributors please add @joshtsch  for doc

**Pull request merged**
