### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by garricn**

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @garricn -

Thanks for the contribution! lgtm :)

**Comment by adilanchian** [comment]
@all-contributors please add @garricn for doc

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

**Comment by garricn** [comment]
My pleasure. Thank you 😊

**Pull request merged**
