### PR TITLE
Update Lesson_4_Let_Users_Vote_On_Proposals.md

### PR DESCRIPTION
**Pull request by rajkharvar**
The promise from `voteModule.hasVoted` returns `boolean`. If the user has already voted then the `hasVoted` flag would be `true` else `false`.

As per the current page, whether the user has voted or noted it prints **🥵 User has already voted**. As a result, it would be good if we add a condition for the console so that at least the developer won't get confused while checking voteStatus.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @rajkharvar -

Thanks for the change here! This LGTM. Going to tag @nachoiacovino here for final thoughts :)

**Comment by adilanchian** [comment]
Hey @rajkharvar -

Thanks for the changes! Will go ahead and get this in :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

**Comment by adilanchian** [comment]
@all-contributors please add @rajkharvar  for doc

**Comment by rajkharvar** [comment]
> Hey @rajkharvar -
> 
> Thanks for the changes! Will go ahead and get this in :)



> ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION
> 
> 🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

Thank you so much @adilanchian😊

**Pull request merged**
