### PR TITLE
Update Lesson_2_Meta_learning_Bow_to_AI.md

### PR DESCRIPTION
**Pull request by neddinn**
Looks like there's a dangling prompt erroneously left there.

### CODE REVIEW

**Review by helloitsm3 — COMMENTED** [review]
Why is this wrong? 🤔

**Comment by neddinn** [comment]
> Why is this wrong? 🤔

In this example of `single-shot learning`, a `prompt:` `story:` mode is used. To quote just the next line below this, 
`I explicitly use Prompt: and Story: just so GPT-3 knows where the last story stopped, and where the next one should start.`

In this case, though, there is a prompt there without use because using it before the `prompt:` makes it a part of the previous story, and that's how I can tell it was left there erroneously maybe while copying from playground?

**Comment by alexisweill** [comment]
Agreed with this change - I created a similar pr before realizing you already had open one so closing mine (https://github.com/buildspace/buildspace-projects/pull/1517)

**Comment by helloitsm3** [comment]
Thanks for this. Will merge it

**Review by helloitsm3 — APPROVED** [review]

**Comment by helloitsm3** [comment]
@all-contributors please add 
@neddinn for docs

**Pull request merged**
