### PR TITLE
Fix minor typo in word

### PR DESCRIPTION
**Pull request by avila-lucas**
Just fixing a small typo in the word Successfully 🙈

### CODE REVIEW

**Review by nachoiacovino — APPROVED** [review]

**Comment by adilanchian** [comment]
Hey @avila-lucas -

BIG RIP. Spelling is hard sometimes haha. Thanks so much for this!!

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by adilanchian** [comment]
@all-contributors please add @avila-lucas for doc

**Comment by avila-lucas** [comment]
Thanks folks 😄 !!! 🚀

**Pull request merged**
