### PR TITLE
Update Lesson_1_Deploy_NFT_Bundle.md

### PR DESCRIPTION
**Pull request by Kevin-Heleodoro**
sdk initiliazation was throwing errors for some users. @mheave on Discord came up with this solution and it solves the issue.

Link to original message:
https://discord.com/channels/869321815833575434/869331605662101546/930441532673261569

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
@nachoiacovino thoughts?

**Comment by nachoiacovino** [comment]
> @nachoiacovino thoughts?

Let me test it out and I'll circle back.

**Comment by nachoiacovino** [comment]
that message is from January, are people having issues after v2 was updated? @Kevin-Heleodoro

**Comment by Kevin-Heleodoro** [comment]
I started running through the tutorial yesterday night and was still having the issue. Once I switched my code, it solved it.

**Review by AlmostEfficient — APPROVED** [review]

**Comment by AlmostEfficient** [comment]
Thank you so much!

**Pull request merged**
