### PR TITLE
edit "moving right a long" to "moving right along"

### PR DESCRIPTION
**Pull request by julianeon**
The correct spelling of this phrase is "moving right along;" I changed it to be that.

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @julianeon !

Thanks for the change here :). Indeed this is the way

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷🥷

**Comment by adilanchian** [comment]
@all-contributors please add @julianeon for doc

**Comment by julianeon** [comment]
Thank you! I'm happy my contribution was helpful; I hope to make more.

**Pull request merged**
