### PR TITLE
fixed a typo - Solana_And_Web3/en/Section_3/Lesson_3_Submitting_GIF_To_Solana

### PR DESCRIPTION
**Pull request by halaprix**
---
name: "✨ typo"
about: typo in one wrod
title: "✨Solana and WEB3: SECTION_3 - Lesson_3_Submitting_GIF_To_Solana"
labels: improvement
assignees: adilanchian, farzaa, emboslicev2

---

### What You Are Changing
*changed `form` to `from` in `being retrieved form your Solana program :)`*

### Anything else?
*I'll find more. Fear not.*

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @halaprix !

Thanks for the catch here (it's a good one!)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

**Comment by adilanchian** [comment]
@all-contributors please add @halaprix  for doc

**Comment by halaprix** [comment]
It was a pleasure ;)

**Pull request merged**
