### PR TITLE
Defer referencing `connected` yet until it defined in the scope

### PR DESCRIPTION
**Pull request by samnang**
When I work through the content, I noticed there is a reference to `connected` variable before it hasn't yet been defined in the scope until a few sections further in the lesson. We should better remove the references and keep the app running build successful and reference it in the same section we define it.

```js
{!connected && <Disconnected />} // connected is not defined yet
```
Until few sections later, it is defined here:

```js
const { connected } = useWallet()

...

{connected ? <Connected /> : <Disconnected />}
```

### CODE REVIEW

**Comment by helloitsm3** [comment]
Thank you so much for this. However, since it's going to get implemented in the later section, do you think it's better to have it included here first instead of removing the variable?

**Comment by samnang** [comment]
It might be okay to leave it there if we keep guiding people keep following step by step without mentioning the running server yet, but I went through the content and mentioned checking the server, I saw the error and a bit confused because I didn't know where `connected` came from.

image

**Comment by helloitsm3** [comment]
> It might be okay to leave it there if we keep guiding people keep following step by step without mentioning the running server yet, but I went through the content and mentioned checking the server, I saw the error and a bit confused because I didn't know where `connected` came from.
> 
> image

You're right about this. It can be confusing. Can I trouble you to remove that line that says "Look at localhost:3000" and add an additional note to mention that they will see an error now but they can fix it in the later section? Thanks

**Comment by samnang** [comment]
> You're right about this. It can be confusing. Can I trouble you to remove that line that says "Look at localhost:3000" and add an additional note to mention that they will see an error now but they can fix it in the later section? Thanks

When I looked at places that referenced `connected` again, I saw two places. From my suggestion, keeping the flow with working version of the app might be better for readers. Even if we tried to say it is okay to see the error about `connected`, readers might be confused because we never explain why it is needed. Finally, if we look at the screenshot below which is where it is mentioned and defined, it explains clearly why it's needed, so we don't see much needed to introduce this variable early in the top section.

image

**Review by helloitsm3 — APPROVED** [review]
LGTM

**Pull request merged**
