### PR TITLE
Fix typo in replit environment variable footnote

### PR DESCRIPTION
**Pull request by awaxman11**
Feel free to reject if you don't like how I adjusted this. It's not super clear what the intended sentence was, but there seems to be a typo in the current form.

### CODE REVIEW

**Review by nachoiacovino — CHANGES_REQUESTED** [review]
delete "then"

**Review by nachoiacovino — APPROVED** [review]
lgtm

**Comment by adilanchian** [comment]
Hey @awaxman11 -

Thanks for the change! Also, thanks @nachoiacovino for taking a look here!

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈

**Comment by adilanchian** [comment]
@all-contributors please add @awaxman11  for doc

**Pull request merged**
