### PR TITLE
Adding Cadence plugin information for the IntelliJ platform

### PR DESCRIPTION
**Pull request by michaelvogt**
As an alternative to VS Code

### CODE REVIEW

**Comment by AlmostEfficient** [comment]
Hey Michael! Thanks a bunch for this, I didn't realise IntelliJ was supported too. Could you let me know if you've tested it on Windows and if there are any problems with the extension?

**Comment by michaelvogt** [comment]
Slowly moving through the 'tutorial', realizing that the VSCode plugin is more functional than the IntelliJ plugin at the moment. Need to execute the deploy and transaction commands directly with the CLI

**Comment by AlmostEfficient** [comment]
I've updated the PR to mention that this exists but it isn't tested so people can make the decision on their own. If someone uses IntelliJ, I trust they know what they're doing lol.

Thanks a bunch for this!

**Review by AlmostEfficient — APPROVED** [review]

**Comment by michaelvogt** [comment]
> I've updated the PR to mention that this exists but it isn't tested so people can make the decision on their own. If someone uses IntelliJ, I trust they know what they're doing lol.
> 
Cool 👍


> Thanks a bunch for this!
My pleasure

**Comment by michaelvogt** [comment]
> I've updated the PR to mention that this exists but it isn't tested so people can make the decision on their own. If someone uses IntelliJ, I trust they know what they're doing lol.
> 
Cool 👍


> Thanks a bunch for this!
My pleasure

**Pull request merged**
