### PR TITLE
Update Lesson_3_Connect_Wallet_To_Web_App.md

### PR DESCRIPTION
**Pull request by jpatel3**
Updated as per correct file format on Replit. mostly its easy to understand, but still to make it less confusing.

### CODE REVIEW

**Review by adilanchian — APPROVED** [review]
Hey !

Thanks for this! Since we are specifically calling out Replit here - probably makes sense to make this change :). 

Thanks!

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️☝️

**Comment by adilanchian** [comment]
@all-contributors please add @jpatel3  for doc

**Comment by jpatel3** [comment]
Thanks for accepting the pull request and making this super fun and informative resource.

**Pull request merged**
