### PR TITLE
Update Lesson_4_Create_A_Contract_That_Mints_NFTs.md

### PR DESCRIPTION
**Pull request by pietroanello**
Added OpenSea "Metadata Standard" info, avoiding errors when trying to see the NFT on the website.

### CODE REVIEW

**Review by helloitsm3 — APPROVED** [review]
Seems like this might be useful for people

**Comment by adilanchian** [comment]
Hey @pietroanello !

Sorry for the late reply here :). Ya this is cool! Small littler reminder is always helpful!

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST GITHUB CONTRIBUTION EVER. OMG AND IT'S WITH US <333

🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈

**Comment by adilanchian** [comment]
@all-contributors please add @pietroanello for doc

**Pull request merged**
