### PR TITLE
JS_DAO/Section_4/Lesson_1 - fix typos

### PR DESCRIPTION
**Pull request by ihanif**
- Change 'your revoke your' to 'you revoke your'
-  Change 'token' to 'tokens' where applicable/correct

### CODE REVIEW

**Review by nachoiacovino — APPROVED** [review]
lgtm!

**Comment by adilanchian** [comment]
Hey @ihanif -

Thanks for the change here!

Good catch!

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR VERY FIRST GITHUB CONTRIBUTION

😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎

**Comment by adilanchian** [comment]
@all-contributors please add @ihanif for doc

**Pull request merged**
