### PR TITLE
Added node to node scripts/8-deploy-vote.js

### PR DESCRIPTION
**Pull request by vplasencia**
Added node to copy the line to run the file.

### CODE REVIEW

**Review by nachoiacovino — APPROVED** [review]
lgtm thanks!

**Comment by adilanchian** [comment]
Hey @vplasencia -

Thanks for this change! Looking good :)

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRT CONTRIBUTION

🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄V

**Comment by adilanchian** [comment]
@all-contributors please add @vplasencia for doc

**Comment by vplasencia** [comment]
Thank you @adilanchian, I really appreciate it. Yes, it's my first contribution :). It's such an honor for me to contribute to this amazing project 🦄

**Pull request merged**
