### PR TITLE
Fix typo errors on the Wave App - section 4 - lesson 1

### PR DESCRIPTION
**Pull request by Uniqcoda**
I saw some grammatical errors and decided to fix them :)

### CODE REVIEW

**Review by adilanchian — APPROVED** [review]
You're amazing!!

Thanks for fixing this issues :). Always hard ones to catch haha

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION 

✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨

**Comment by adilanchian** [comment]
@all-contributors please add @Uniqcoda  for doc

**Comment by Uniqcoda** [comment]
Thank you @adilanchian :)

**Pull request merged**
