### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by directdetour**

### CODE REVIEW

**Review by garyghayrat — APPROVED** [review]
Thank you

**Comment by adilanchian** [comment]
Hey @directdetour !

Thanks for the PR my friend & sorry for the late reply here!!

Good catch ty :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄

**Comment by adilanchian** [comment]
@all-contributors please add @directdetour  for doc

**Comment by directdetour** [comment]
Ha! thanks so much, I'm really enjoying learning on buildspace! happy to help :)

**Pull request merged**
