### PR TITLE
Small Suggestion

### PR DESCRIPTION
**Pull request by yanukadeneth99**

### CODE REVIEW

**Comment by helloitsm3** [comment]
By typing the Ubuntu command, it'll be in Ubuntu environment so this is kinda redundant

**Comment by yanukadeneth99** [comment]
You can't open the ``\\wsl$\Ubuntu` folder unless the Ubuntu terminal is running. The folder will not exist. That's what I wanted to say there.

**Comment by helloitsm3** [comment]
> You can't open the `\\wsl$\Ubuntu` folder unless the Ubuntu terminal is running. The folder will not exist. That's what I wanted to say there. @helloitsm3

hmmm I don't have my Ubuntu terminal running but I'm able to access it
image

**Comment by yanukadeneth99** [comment]
Interesting. I have this before running WLS. One thread to make sure Ubuntu terminal is running. 
Screenshot_1

**Comment by helloitsm3** [comment]
> Interesting. I have this before running WLS. One thread to make sure Ubuntu terminal is running. 
> 
> Screenshot_1
> 
> 

No harm having an additional text to make sure people are able to connect I guess. I'll see if I can help you get this merged 👍

**Review by AlmostEfficient — APPROVED** [review]

**Pull request merged**
