### PR TITLE
Update m1_setup.md

### PR DESCRIPTION
**Pull request by moflo**
Recommend specifying v0.18.0 for the anchor install as other version seem to cause the program-ID issue

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @moflo -

Thanks for the suggestion here :). Could you give me a little more context on this `program-ID` issue?

**Comment by adilanchian** [comment]
Sup @moflo !

Just dropping a ping here to see if you need help with anything?

**Comment by moflo** [comment]
Sorry for the delay, this was in regards to issues running on the newest Apple M1 silicon, and the fix was to rollback a version of Anchor by specifying it explicitly. I suspect the underlying issue is due to a problem with the IDL JSON file which was introduced in a later version of Anchor but I didn't have time to investigate. Thanks!

**Comment by adilanchian** [comment]
Hey @moflo !

Thanks for the insight here :). Okay cool good to know! 

@NickGonzalez04 is our M1 guru so will see if he has some time to give this a quick test :)

**Comment by NickGonzalez04** [comment]
Hey @moflo ! Going to test the version you recommend switching to. Just wanted to ask what error was happening for you to do a rollback so I know what to look for! Thanks!

**Comment by adilanchian** [comment]
Hey @moflo -

Going to close this out based on no activity :). Feel free to re-open this PR if you feel strongly about it!!

**Pull request closed without merging**
