### PR TITLE
fix: no need for _totalSupply parameter when verifying the contract.

### PR DESCRIPTION
**Pull request by moojing**
# Problem 
when I was doing the contract verification I encountered an error with the command on the lecture. 
Screen Shot 2021-11-23 at 10 06 38 PM

after some research, I thought that maybe we don't need the argument '_totalSupply'?

#Refs 
https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html#usage

### CODE REVIEW

**Comment by adilanchian** [comment]
hey @moojing !

Thanks for the submission here :). Did you end up trying to run this command without the `_totalSupply` flag? Curious if it worked or not? The error would definitely point to idea of that not being needed!

**Comment by moojing** [comment]
@adilanchian  yes, after removing the `_totalSuppy` then everything goes well. 
and the constructor on the contract is 
```
constructor() ERC721("SquareNFT", "SQUARE") {
        console.log("This is my NFT contract. Woah!");
    }
```
you can see that there are no arguments for the constructor. 
I got involved with the class just recently, so I'm not sure it's actually a problem or not 🤔

**Comment by ACollectionOfAtoms** [comment]
Came here to make the same PR! Thanks @moojing 

Also can confirm, `_totalSupply` seems to be erroneous

**Review by adilanchian — APPROVED** [review]
Thank you all for the heads up here! Will go ahead and get this in :).

**Comment by adilanchian** [comment]
@moojing CONGRATS ON YOUR FIRST CONTRIBUTION!!

@ACollectionOfAtoms Thanks for coming through on this!

🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐🐐

**Comment by adilanchian** [comment]
@all-contributors please add @moojing for doc

**Comment by adilanchian** [comment]
@all-contributors please add @ACollectionOfAtoms  for doc

**Comment by moojing** [comment]
@ACollectionOfAtoms  @adilanchian great. let's keep going and learning!

**Pull request merged**
