### PR TITLE
CREATE License

### PR DESCRIPTION
**Pull request by thesoorajsingh**
Added an MIT open source License to the project to help maintain a set standards for contributors

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @thesoorajsingh -

Thanks for this addition! Def needed :)

**Comment by adilanchian** [comment]
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

**Comment by adilanchian** [comment]
@all-contributors please add @thesoorajsingh  for doc

**Comment by thesoorajsingh** [comment]
> ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION
> 
> 🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶

Thanks! @adilanchian looking forward to many more!

**Pull request merged**
