### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by ellyg123**
Hey, just found a tiny typo :)

### CODE REVIEW

**Comment by adilanchian** [comment]
Hey @ellyg123 !!

INDEED that is not ideal haha. Thanks so much for this!

**Comment by adilanchian** [comment]
@all-contributors please add @ellyg123 for doc

**Comment by adilanchian** [comment]
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘🤘

**Comment by ellyg123** [comment]
lol thank you!! my first one let's gooo!! 🦄 🦄 🦄 🦄

**Pull request merged**
