### PR TITLE
machineState ui bug

### PR DESCRIPTION
**Pull request by sayantank**
Just a small refactor to prevent React from error-ing out in case `machineState` is `null`.

### CODE REVIEW

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hey @sayantank !

Nice catch here and sorry for the late reply!!

Can you do me a huge favor - can you verify that this code block is updated throughout this project? Can't remember if this was used in other code blocks!

**Comment by adilanchian** [comment]
Hey @sayantank -

Friendly ping on this if you are still wanting to do it!

**Comment by sayantank** [comment]
Hey, yeah I can take this up! I was actually occupied with my exams, which are done now. So, I'll have a look and make further changes if needed 😃

**Comment by adilanchian** [comment]
Hey @sayantank -

Hope exams went well!! thank you :)

**Comment by sayantank** [comment]
Hi, I think the project has been correctly updated already. I've gone through the code snippets and everything seems to be fine! 😄

**Pull request closed without merging**
